### ISSUE TITLE
/root/pool/node_modules/mailgun.js/lib/client.js:18 error 

### ISSUE THREAD

**Issue by zhiapp-com** [sumoprojects/cryptonote-sumokoin-pool#22]
/root/pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

2018-02-07 00:52:10 [master] API died, spawning replacement...
2018-02-07 00:52:12 [charts] Started

i used node v0.10.48

**Comment by dvandal** [comment]
The code require Node.js version 4.x or later, updating Node.js and npm will fix your issue

**Comment by mobbil** [comment]
i have same problem using Node version 4.x later updated the node.js and npm but didnt fixed can you send step by step to fi please
